services:
  untracer_single:
    build:
      context: .
    platform: linux/amd64
    stdin_open: true
    tty: true


# # Build a specific service
# docker compose build xpdf-angora

# # Build all services
# docker compose build